name: Docker Build and Release
on: [ push ]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    #### AUFGABE 2: SONAR
      # hier kommt die Konfiguration der Sonar-Analyse rein
  
    - name: Compile, build and push
      run: |
        #### AUFGABE 3 COMPILE, DOCKER BUILD UND PUSH
          # an dieser Stelle wird die Aufgabe 3 bearbeitet: maven package, docker build, docker push
